# Generated by Django 4.2.10 on 2024-02-13 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="product", name="product_id",),
        migrations.AlterField(
            model_name="product",
            name="description",
            field=models.CharField(blank=True, default="", max_length=50, null=True),
        ),
    ]
